<?php 
	/**
	 * The forgot password form...
	 * @var Owner_ForgotPassword
	 */
	$form = $this->form;

?>

<div id="container">
	<div class="owner-login">
		<?php echo $this->partial('include/owners/login-link.phtml')?>
		<div class="login-form">
			<h1>Forgot your password?</h1>
			<form method="<?php echo $form->getMethod()?>" id="login-form">
				<div class="control-set">
					<dl>
						<dt>
							Email Address
						</dt>
						<dd class="last">
							<?php echo $form->email_address->renderViewHelper()?>	
						</dd>				
					</dl>
				</div>
				<div class="button-radio-set">
					Send it to my email
				</div>
				<button type="submit">Submit</button>
			</form>
		</div>
	</div>
</div>