<div id="container">
	<div class="owner-login">
		<?php echo $this->partial('include/owners/login-link.phtml')?>
		<div class="login-form">
			<h1>Forgot your password?</h1>
			<form method="post" id="login-form">
				<div class="control-set">
					<dl>
						<dt>
							Email Address
						</dt>
						<dd class="last">
							<input type="text" name="email"/>
						</dd>				
					</dl>
				</div>
				<div class="button-radio-set">
					Send it to my email
				</div>
				<button type="submit">Submit</button>
			</form>
		</div>
	</div>
</div>