<div id="container">
	<header>
		<img src="/public/images/logo.png" alt="Logo"/>
	</header>
	<div id="main-container">
		<nav id="main-navigation">
			<div class="navigation">
				<br/>
				<img src="<?php echo $this->baseUrl?>/images/home.png" alt="Home"/>						
			</div>
			<div class="navigation">
				<br/>
				<img src="<?php echo $this->baseUrl?>/images/user.png" alt="User Groups"/><br/>
				User Groups
			</div>
			<div class="navigation">
				<br/>
				<img src="<?php echo $this->baseUrl?>/images/socket.png" alt="Your Plugin"/><br/>
				Your Plugin
			</div>
			<div class="navigation">
				<br/>
				<img src="<?php echo $this->baseUrl?>/images/mobile.png" alt="Leads Chat"/><br/>
				Leads Chat
			</div>
			<div class="navigation">
				<br/>
				<img src="<?php echo $this->baseUrl?>/images/settings.png" alt="Settings"/><br/>
				Settings
			</div>
		</nav>	
		<div id="main-panel">
			<div id="main-panel-container-header">
				<button class="toggle">
					Newly Delivered
				</button>
				<button class="toggle">
					Your Leads
				</button>
				<div class="leads-counter">
					<img class="icon" src="images/chat-bubble.png"/>
					<h2>You have <span class="days color">14</span> days in Your <span class="days color">Free Trial</span> with unlimited leads</h2>
				</div>
				
			</div>
				
			<div id="leads-list">
				<div class="lead">
					<div class="button-set">
						<button class="buy">BUY Lead</button>
					</div>
					<div class="date">
							<span class="date-label">Date: </span><span class="date">April 14, 2012</span>
					</div>
					<div class="message">
						"We have delivered <span class="color">20</span> leads"
					</div>
				</div>
				<div class="lead alt-row">
					<div class="button-set">
						<button class="buy">BUY Lead</button>
					</div>
					<div class="date">
							<span class="date-label">Date: </span><span class="date">April 14, 2012</span>
					</div>
					<div class="message">
						"We have delivered <span class="color">20</span> leads"
					</div>
				</div>
				<div class="lead">
					<div class="button-set">
						<button class="buy">BUY Lead</button>
					</div>
					<div class="date">
							<span class="date-label">Date: </span><span class="date">April 14, 2012</span>
					</div>
					<div class="message">
						"We have delivered <span class="color">20</span> leads"
					</div>
				</div>
				<div class="lead alt-row">
					<div class="button-set">
						<button class="buy">BUY Lead</button>
					</div>
					<div class="date">
							<span class="date-label">Date: </span><span class="date">April 14, 2012</span>
					</div>
					<div class="message">
						"We have delivered <span class="color">20</span> leads"
					</div>
				</div>
				<div class="lead">
					<div class="button-set">
						<button class="buy">BUY Lead</button>
					</div>
					<div class="date">
							<span class="date-label">Date: </span><span class="date">April 14, 2012</span>
					</div>
					<div class="message">
						"We have delivered <span class="color">20</span> leads"
					</div>
				</div>
				<div class="lead alt-row">
					<div class="button-set">
						<button class="buy">BUY Lead</button>
					</div>
					<div class="date">
							<span class="date-label">Date: </span><span class="date">April 14, 2012</span>
					</div>
					<div class="message">
						"We have delivered <span class="color">20</span> leads"
					</div>
				</div>
				<div class="total-leads">
					
					<div class="label-counter">
						Total Leads: <span class="label">6</span>
					</div>
					<div class="button">
						<button id="buy-leads">
							BUY all Leads
						</button>
					</div>
				</div>
				<div class="more">
					<span>MORE</span>
					<img src="<?php echo $this->baseUrl?>/images/more.png"/>
				</div>
			</div>
		</div>
		<div id="owner-info-panel">
			<div class="info">
				<div class="picture-container"></div>
				<div class="info-container">
					<div>
						<span class="color">Hi</span>, Allanaire	
					</div>
					<div class="free-trial-use">
						Free Trial User
					</div>
					<div class="small">
						You just got
					</div>
					<div class="leads-label last">
						200 <strong>Leads</strong>
					</div>
				</div>
				<div class="address">
					Blck 2 Lot 8, Villa Edlimar Philippines
				</div>							
			</div>
			<div class="shadow"></div>
			<div class="logout">
				<img src="<?php echo $this->baseUrl?>/images/turnoff.png"/><span>Logout</span>
			</div>
		</div>
	</div>
</div>