<?php 
	$owner = $this->owner;
?>
<div class="wrapper">
	<?php echo $this->partial('include/owners/index-header.phtml');?>
	<div id="main-container" class="main-container">

		<?php echo $this->partial("include/owners/index-sidebar.phtml")?>
		<div id="main-content-container" class="main-content-container">
			<div id="main-content-container-pointer"
				class="main-content-container-pointer"></div>
			<div id="main-content-container-body" class="main-content-container-body">
			
			
			
			</div>

		</div>
		<div id="navigation-main-right" class="navigation-main-right">
			<div id="contact-info" class="contact-info">
				<div class="info">
					<span><span class="darkblue">Hi,</span> <span id="member-name"><?php echo $owner["first_name"]." ".$owner["last_name"]?></span></span><br />
					
					<?php
						$class = ""; 
						if ($owner["free_trial"]){
							$class = "free-trial";
							$text = "Free Trial User";		
						}else{
							
							if ($owner["paying_service_type"]=="PAY AS YOU GO"){
								$class = "pay-as-you-go";
								$text = "Pay As You Go";
							}else{
								$class = "bulk-subscriber";
								$text = "Bulk Subscriber";
							}
						}
					?>
					<button class="button-trial <?php echo $class?>"><?php echo $text?></button>
					<?php if ($owner["paying_service_type"]=="BULK SUBSCRIBER"){?>
						<p>You still have,</p>
						<p>
							<?php echo $owner["credits"]?> <span class="darkblue">Credits.</span> remaining.
						</p>
					<?php }?>
				</div>
				<div class="picture-frame">
					<img src="images/danilo.jpg" />
				</div>
				<div class="spacer"></div>
				<div class="address"><?php echo $owner["website"]?></div>
			</div>

			<div id="chat-area" class="chat-area">
				<h2 class="contacts">
					<img src="images/chat.png" /><span>CONTACTS</span>
				</h2>
				<div class="line"></div>
				<ul class="chat-list" id="online-list">
				
				</ul>
				<h3 class="offline-header">
					<span>Offline</span>
					<div class="line"></div>
				</h3>
				<ul class="chat-list" id="offline-list">
					
				</ul>

			</div>
		</div>


	</div>


	<div class="push"></div>
</div>
<?php 
	echo $this->partial("include/owners/index-footer.phtml");
?>