<?php 
	$form = $this->form;
?>
<div id="container">
	<div class="owner-login">	
		<?php echo $this->partial('include/owners/login-link.phtml')?>
		<div class="login-form">
			<h1>Signing in to your Account</h1>
			<form method="<?php echo $form->getMethod()?>" id="login-form">
				<div class="control-set">
					<dl>
						<dt>
							Username
						</dt>
						<dd>
							<?php echo $form->username->renderViewHelper()?>
						</dd>			
						<dt>
							Password
						</dt>
						<dd class="last">
							<?php echo $form->password->renderViewHelper()?>
						</dd>						
					</dl>
				</div>
				<div class="button-radio-set">
					<?php echo $form->remember_me->renderViewHelper()?> Remember me
				</div>
				<button type="submit">Submit</button>
			</form>
		</div>
	</div>
</div>