<?php 
	$form = $this->form;
?>
<div class="container container-progress"><img src="/images/owners/register/step-2-progress.png" alt="Step 1"/>
</div>
<div class="container step-form">
	<form>
		<div class="well">
			<h1><img src="/images/owners/register/2-3.png" alt="2 out of 3"/>Company Information</h1>
			<label>Company Name</label>
			<?php echo $form->company->renderViewHelper()?>
			<label>Business Type</label>
			<input type="text" class="span4"/>
			<label>What time zone is your business located?</label>
			<input type="text" class="span4"/>
			<label>Website/URL <strong>e.g.leadschat.com</strong></label>
			<input type="text" class="span4"/>
			<label>How many web hits do you currently receieve each month?</label>
			<input type="text" class="span4"/>
			<label>Contact <strong>(Skype, Mobile)</strong></label>
			<input type="text" class="span4"/>
			<label>Address 1</label>
			<input type="text" class="span6"/>
			<label>Address 2</label>
			<input type="text" class="span6"/>
			<div class="two-row form-inline well">
				<label class="span4">City</label><label class="span2">Postal</label>
				<br/>
				<input type="text" class="span4"/>
				<input type="text" class="span2"/>
			</div>
			<label>State</label>
			<input type="text" class="span4"/>
			<label>Country</label>
			<input type="text" class="span4"/>
		</div>
		<div class="submit-form">
			<button type="submit" class="btn btn-primary">
				Save and Continue <i class="arrow-next"></i>
			</button>
		</div>
	</form>
</div>
<div class="shadow container"></div>