<?php 
	$form = $this->registration_form;
?>
<script type="text/javascript">
	var timezones = <?php echo json_encode($this->timezoneGroups)?>;
</script>

<div id="container">
	<header>
		<a href="/"><img src="/public/images/logo.png" alt="Logo"/></a>
	</header>
	<div class="signup-form-design"></div>
	
	<div class="registration-form">
		<form method="<?php echo $form->getMethod()?>" id="registration-form">
			<div class="control-set">
				<dl>
					<?php echo $form->getElement("first_name")->render()?>
					<?php echo $form->getElement("last_name")->render()?>						
				</dl>
			</div>
			<div class="control-set">
				<dl>
					<?php echo $form->password->render()?>
					<?php echo $form->confirm_password->render();?>						
				</dl>
			</div>
			<div class="control-set">
				<dl>
					<?php echo $form->getElement("email")->render()?>
					<?php echo $form->getElement("username")->render()?>
				</dl>
			</div>
			<div class="control-set">
				<dl>
					<?php echo $form->getElement("business_type")->render()?>
					<?php echo $form->getElement("timezone_id")->render()?>
					<?php echo $form->getElement("website")->render()?>
					<?php echo $form->getElement("number_of_hit_id")->render()?>
					<?php echo $form->getElement("company")->render()?>
					<?php echo $form->getElement("mobile")->render()?>
				</dl>
			</div>
			<div class="control-set">
				<dl>
					<?php echo $form->getElement("fullname_webmaster")->render()?>
					<?php echo $form->getElement("email_webmaster")->render()?>
					<?php echo $form->getElement("phone_webmaster")->render()?>
				</dl>
			</div>
			<div class="control-set">
				<dl>
					<dd class="accept">
						<?php echo $form->getElement("accept")->renderViewHelper()?> I Accept, the Terms and Service
					</dd>
				</dl>
			</div>
			<div class="button-container">
				<button type="submit">
					Submit
				</button>
			</div>					
		</form>
	</div>
</div>