<div class="container container-progress"><img src="images/register/step-3-progress.png" alt="Step 1"/>
</div>
<div class="container step-form">
	<form>
		<div class="well">
			<h1><img src="images/register/3-3.png" alt="3 out of 3"/>Company’s Web Designer Information</h1>
			<label>Name</label>
			<input type="text" class="span4"/>
			<label>Email</label>
			<input type="text" class="span4"/>
			<label>Phone Number</label>
			<input type="text" class="span4"/>
			<label>Contact Number <strong>e.g. Skype, YM, Gtalk</strong></label>
			<input type="text" class="span4"/>
		</div>
		<div class="submit-form">
			<aside class="aside span-4">
				<input type="checkbox"/>
				&nbsp;I Accept, the <a href="#">Terms of Service</a>
			</aside>
			<button type="submit" class="btn btn-primary">
				Save and Continue <i class="arrow-next"></i>
			</button>
		</div>
	</form>
</div>
<div class="shadow container"></div>