<?php 
	$form = $this->form;
?>
<div class="container container-progress"><img src="/images/owners/register/step-1-progress.png" alt="Step 1"/>
</div>
<div class="container step-form">
	<form method="<?php echo $form->getMethod()?>" id="registration-form-1">
		<div class="well">
			<h1><img src="/images/owners/register/1-3.png" alt="1 out of 3"/>Account Information</h1>
			<div class="control-group">
				<label class="control-label" for="first_name">First name</label>
				<div class="controls">
					<?php echo $form->first_name->renderViewHelper();?>
				</div>	
			</div>
			<div class="control-group">
				<label class="control-label" for="last_name">Last name</label>
				<div class="controls">
					<?php echo $form->last_name->renderViewHelper();?>
				</div>			
			</div>
			<div class="control-group">
				<label class="control-label" for="email">Email Address</label>
				<div class="controls">
					<?php echo $form->email->renderViewHelper();?>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="confirm_email">Confirm Email Address</label>
				<div class="controls">
					<?php echo $form->confirm_email->renderViewHelper();?>
				</div>
				
			</div>
		</div>
		<div class="submit-form">
			<button type="submit" class="btn btn-primary">
				Save and Continue <i class="arrow-next"></i>
			</button>
		</div>
	</form>
</div>
<div class="shadow container"></div>