<?php 
	$form = $this->form;
?>
<div class="container container-progress"><img src="/images/owners/register/step-2-progress.png" alt="Step 1"/>
</div>
<div class="container step-form">
	<form method="<?php echo $form->getMethod()?>" id="registration-form-2">
		<div class="well">
			<h1><img src="/images/owners/register/2-3.png" alt="2 out of 3"/>Company Information</h1>
			<div class="control-group">
				<label>Company Name</label>
				<?php echo $form->company->renderViewHelper()?>
			</div>
			<div class="control-group">
				<label>Business Type</label>
				<?php echo $form->business_type->renderViewHelper()?>
			</div>
			<div class="control-group">
				<label>What time zone is your business located?</label>
				<?php echo $form->timezone_id->renderViewHelper()?>
			</div>
			<div class="control-group">
				<label>Website/URL <strong>e.g.leadschat.com</strong></label>
				<?php echo $form->website->renderViewHelper()?>
			</div>
			<div class="control-group">
				<label>How many web hits do you currently receieve each month?</label>
				<?php echo $form->number_of_hit_id->renderViewHelper()?>
			</div>
			<div class="control-group">
				<label>Contact <strong>(Skype, Mobile)</strong></label>
				<?php echo $form->mobile->renderViewHelper()?>
			</div>
			<div class="control-group">
				<label>Address 1</label>
				<?php echo $form->address1->renderViewHelper()?>
			</div>
			<div class="control-group">
				<label>Address 2</label>
				<?php echo $form->address2->renderViewHelper()?>
			</div>
			<div class="two-row form-inline well">
				<label class="span4">City</label><label class="span2">Postal</label>
				<br/>
				<?php echo $form->city->renderViewHelper()?>
				<?php echo $form->postal->renderViewHelper()?>
			</div>
			<div class="control-group">
				<label>State</label>
				<?php echo $form->state->renderViewHelper()?>
			</div>
			<div class="control-group">			
				<label>Country</label>
				<?php echo $form->country_id->renderViewHelper()?>
			</div>
		</div>
		<div class="submit-form">
			<button type="submit" class="btn btn-primary">
				Save and Continue <i class="arrow-next"></i>
			</button>
		</div>
	</form>
</div>
<div class="shadow container"></div>