<div class="container container-progress"><img src="images/register/step-1-progress.png" alt="Step 1"/>
</div>
<div class="container step-form">
	<form>
		<div class="well">
			<h1><img src="images/register/1-3.png" alt="1 out of 3"/>Account Information</h1>
			<label>First name</label>
			<input type="text" class="span4"/>
			<label>Last name</label>
			<input type="text" class="span4"/>
			<label>Email Address</label>
			<input type="text" class="span4"/>
			<label>Confirm Email Address</label>
			<input type="text" class="span4"/>
		</div>
		<div class="submit-form">
			<button type="submit" class="btn btn-primary">
				Save and Continue <i class="arrow-next"></i>
			</button>
		</div>
	</form>
</div>
<div class="shadow container"></div>