<div id="container">
	<header>
		<img src="/public/images/logo.png" alt="Logo"/>
	</header>
	<div class="signup-form-design"></div>
	<div class="registration-form">
		<form method="post" id="registration-form">
			<div class="control-set">
				<dl>
					<dt>
						Firstname
					</dt>
					<dd>
						<input type="text" name="first_name"/>
					</dd>			
					<dt>
						Lastname
					</dt>
					<dd class="last">
						<input type="text" name="last_name"/>
					</dd>						
				</dl>
			</div>
			<div class="control-set">
				<dl>
					<dt>
						Email Address
					</dt>
					<dd>
						<input type="text" name="email"/>
					</dd>			
					<dt>
						Username
					</dt>
					<dd class="last">
						<input type="text" name="username"/>
					</dd>						
				</dl>
			</div>
			<div class="control-set">
				<dl>
					<dt>
						Password
					</dt>
					<dd>
						<input type="password" name="password"/>
					</dd>			
					<dt>
						Confirm Password
					</dt>
					<dd class="last">
						<input type="password" name="confirmpassword"/>
					</dd>						
				</dl>
			</div>
			<div class="control-set">
				<dl>
					<dt>
						Business Type
					</dt>
					<dd>
						<select name="owner_type">
							<option>Sales</option>
						</select>
					</dd>			
					<dt>
						Website
					</dt>
					<dd>
						<input type="text" name="website"/>
					</dd>			
					<dt>
						Company(optional)
					</dt>
					<dd>
						<input type="text" name="company"/>
					</dd>
					<dt>
						Mobile(optional)
					</dt>
					<dd>
						<input type="text" name="mobile"/>
					</dd>						
					<dt>
						Number of hits your website receive
					</dt>
					<dd>
						<input type="text" name="number_hits"/>
					</dd>
					<dt>
						Your preferred working timezone
					</dt>
					<dd class="last">
						<select name="working_timezone">
							<option selected>Asia/Manila</option>
						</select>
					</dd>
				</dl>
			</div>
			<div class="button-container">
				<button type="submit">
					Submit
				</button>
			</div>					
		</form>
	</div>
</div>