<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame
		Remove this if you use the .htaccess -->
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<title>Leadschat - Registration Complete</title>
		<meta name="description" content="" />
		<meta name="author" content="Leadschat" />
		<meta name="viewport" content="width=device-width; initial-scale=1.0" />
		<!-- Replace favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
		<link rel="shortcut icon" href="/favicon.ico" />
		<link rel="apple-touch-icon" href="/apple-touch-icon.png" />
		<link rel="stylesheet" href="<?php echo $this->baseUrl?>/css/welcome-stylesheet.css" type="text/css"/>
	</head>
	<body>
		<div class="wrapper">
				
			<div class="push"></div>
		</div>
		<footer>
			<div class="footer-content">
				<div class="logo"></div>
				<div class="links">
					<ul>
						<li><img src="<?php echo $this->baseUrl?>/images/chat-small.png"/><a href="#">About Us</a></li>
						<li class="spacer"></li>
						<li><img src="<?php echo $this->baseUrl?>/images/works.png"/><a href="#">How it works</a></li>
						<li class="spacer"></li>
						<li><img src="<?php echo $this->baseUrl?>/images/paper.png"/><a href="#">Service</a></li>
						<li class="spacer"></li>
						<li><img src="<?php echo $this->baseUrl?>/images/dollar.png"/><a href="#">Pricing</a></li>
					</ul>
				</div>
			</div>
			<div class="wrapper-inside">
				<div class="welcome-container">
					<img src="<?php echo $this->baseUrl?>/images/welcome-leadschat.png"/>
					<a href="/" class="back-to-home"></a>
				</div>	
				<img src="<?php echo $this->baseUrl?>/images/cgirl.png" class="cgirl"/>	
			</div>		
			
		</footer>
	</body>
</html>
