<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame
		Remove this if you use the .htaccess -->
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<?php 
			echo $this->headTitle();
			echo $this->headScript();
			echo $this->headLink();
		?>		
		<meta name="description" content="Leads Chat" />
		<meta name="author" content="Tapion" />
		<meta name="viewport" content="width=device-width; initial-scale=1.0" />
	</head>
	<body>
		<header>
			<div class='logo'><img src='/public/images/leadchat-small.png' alt="Leads Chat"/></div>
			<div class='navigation'>
				<ul>
					<li>Hi, <?php echo $this->user["first_name"]?></li>
					<li><a href='/agents/dashboard'>Home</a></li>
					<li><a href='/agents/conversations'>Conversation</a></li>				
					<?php 
						if ($this->admin){
							?>
								<li><a href='/agents/admin'>Admin</a></li>
							<?php 
						}
					?>
					<li><a href='/agents/settings'>Settings</a></li>
					<li><a href='/agents/logout'>Logout</a></li>
				</ul>
			</div>
		</header>
		<div id="content">
			<?php echo $this->layout()->content?>
		</div>
	</body>
</html>