<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame
		Remove this if you use the .htaccess -->
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<?php 
			echo $this->headTitle();
			echo $this->headLink();
			echo $this->headScript();
		?>		
		<meta name="description" content="Leads Chat" />
		<meta name="author" content="Intuitive Marketing LLC" />
	</head>
	<body>
		<?php echo $this->layout()->content?>
	</body>
</html>