<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Leads Chat</title>
    <link href="css/mailtemplate.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div id="maincontainer">
        <div class="content">
            <div class="clipper">
            </div>
            <!-- end .clipper -->
            <div class="logo">
                <img src="img/leadchatlogo.png" alt="Leads Chat Logo" />
            </div>
            <!-- end .logo -->
            <?php echo $this->layout()->content ?>
        </div>
        <!-- end .content -->
        <div class="copyright">
            © 2012 Copyright Leads CHAT. All rights reserved</div>
        <!-- end .copyright -->
    </div>
    <!-- end .maincontainer -->
</body>
</html>