
<div class="bodywrap">
	<div class="container">
	<?php echo $this->partial('include/index/header.phtml')?>
    
	

	<!-- middle -->

		<div class="middle">


			<!-- content -->

			<div class="wrapper">

				<div class="content">



					<!-- text content -->

					<div class="text">



						<h1>We started with a great idea and tons of enthusiasm.</h1>

						<p class="text-big">Ten years ago a crack commando unit was sent
							to prison by a military court for a crime they didn't commit.
							These men promptly escaped from a maximum security stockade to
							the Los Angeles underground.</p>







						<!-- vertical boxes -->

						<div class="white-box">

							<img src="<?php echo $this->baseUrl()?>/images/about-us.jpg" width="716" height="222" alt="" />

							<div class="vertical-box">

								<h2>We care about the products we build</h2>

								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed
									do eiusmod tempor incididunt ut labore et dolore magna aliqua.
									Ut enim ad minim veniam, quis nostrud exercitation ullamco
									laboris nisi.</p>

							</div>



							<div class="vertical-box">

								<h2>To be passionate is the key</h2>

								<p>Straight'nin' the curve, flat'nin' the hills. Someday the
									mountain might get 'em, but the law never will. Makin' their
									way, the only way they know how, that's just a little bit more
									than the law will allow.</p>

							</div>



							<div class="white-box-bot"></div>

						</div>

						<!--/ vertical boxes -->



						<!-- vertical box 2 -->

						<div class="white-box nobg">

							<h2>Guidelines that we follow:</h2>



							<div class="vertical-box">

								<ul>

									<li><strong>Children of the sun, see your time has just begun.</strong>
										I was sent to prison by a military court for a crime they
										didn't commit.</li>

									<li><strong>Ten years ago a crack commando unit</strong>. I was
										sent to prison by a military court for a crime they didn't
										commit.</li>

									<li><strong>Children of the sun, see your time has just begun.</strong>
										I was sent to prison by a military court for a crime they
										didn't commit.</li>

								</ul>

							</div>



							<div class="vertical-box">

								<ul>

									<li><strong>Children of the sun, see your time has just begun.</strong>
										I was sent to prison by a military court for a crime they
										didn't commit.</li>

									<li><strong>Ten years ago a crack commando unit</strong>. I was
										sent to prison by a military court for a crime they didn't
										commit.</li>

									<li><strong>Children of the sun, see your time has just begun.</strong>
										I was sent to prison by a military court for a crime they
										didn't commit.</li>

								</ul>

							</div>

							<div class="clear"></div>

						</div>

						<!--/ vertical box 2 -->



					</div>

					<!--/ text content -->



				</div>

			</div>



			<!--/ content -->


			<?php echo $this->partial("include/index/content-navigation.phtml")?>

			<div class="clear"></div>

		</div>

		<!--/ middle -->





	</div>

	<!--/ container -->


	<?php echo $this->partial("include/index/footer.phtml")?>



</div>
<?php echo $this->partial("include/index/tracker.phtml")?>



<script type="text/javascript">

var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");

document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));

</script>

<script type="text/javascript">

try {

var pageTracker = _gat._getTracker("UA-15832274-1");

pageTracker._trackPageview();

} catch(err) {}</script>



<script type="text/javascript">

var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");

document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));

</script>

<script type="text/javascript">

try {

var pageTracker = _gat._getTracker("UA-15832274-4");

pageTracker._trackPageview();

} catch(err) {}</script>
