<!-- text content -->
<div class="text">
	<h1>Our Business is Your Business.</h1>
	<p class="text-big">
		At the end of the day, talk doesn’t matter. You crunch data and look at hard numbers. You also analyze what things are working well for your business and what things aren't.  
		<br/>
		<br/>
		So do we.
	<p>
		We know that one of the keys to running a successful business is the rapid sharing of accurate, detailed information. More accurate information and more leads mean more business and more revenue. We only win if you do, so it’s our goal to help you become more efficient and profitable.
	</p>
	</p> <!-- vertical boxes -->
	<div class="white-box">
		<img src="images/about-us.jpg" width="716" height="222" alt="" />
		<div class="vertical-box">
			<h2>Behind LeadsChat...</h2>
			<p>
				Behind LeadsChat are sales and Internet marketing professionals who have worked with Fortune 500 companies and helped increase the bottom line of businesses that are not much different from yours. We know how to increase your efficiency. That’s our sole objective – and the end result is an <strong>increase in your bottom line</strong>. Professionalism and accuracy are living, breathing parts of everything we do.
			</p>
		</div>
		<div class="vertical-box">
			<h2>Try our system FREE for 24 hours</h2>
			<p>
				And you'll see that we're the best partner you could ever have – a business partner with the sole objective of helping you make more money every single day.
				<br/>
				<br/>
				We’re eager to show you how well the LeadsChat system works – <a href="#">click here to contact us now!</a>
			</p>
		</div>
		<div class="white-box-bot"></div>
	</div>
	<!--/ vertical boxes -->

</div>
<!--/ text content -->