<!-- text content -->
<div class="text">
	<h1>Benefits of Live Chat</h1>
	<p class="text-big">
		Think about it: Would you open a store and pay for utilities, furniture, merchandise, and advertising, and then not staff it with anyone to greet and answer questions for your customers? That would be totally crazy, right? Who would want to lose that much business every day?
	</p>
	<p>
		But, in essence, are you doing this with your website right now?
	</p>
	<p>
		With LeadsChat, our trained sales professionals actively engage with your website visitors, answering their questions and gauging their interest. Our team gathers contact information and <strong>passes strong leads on to you immediately,</strong> so you can follow up and make the sale or provide the service they're looking for.
	</p>
	<br/>
	<h1>Take a Look at the Research</h1>
	<!-- horizontal boxes -->
	<!--quested by natalie to be list rather than sections -->
	<ul>
		<li>
			<h4>Making Proactive Chat Work</h4>
			<p style="margin-top: 0;">
				A recent study conducted by Forrester Research entitled “Making Proactive Chat Work” found that “Many online consumers want help from a live person while they are shopping online; in fact, <strong>44% of consumers</strong> say that having <strong>questions answered by a live person</strong> while in the middle of an online purchase is <strong>one of the most</strong> important features a website can offer.”
			</p>
		</li>
		<li>
			<h4>ATG Global Consumer Trend</h4>
			<p style="margin-top: 0;">
				An ATG Global Consumer Trend study found that <strong>90% of customers consider live chat helpful.</strong>
			</p>
		</li>
		<li>
			<h4>Emarketer.com Survey</h4>
			<p style="margin-top: 0;">
				An <a href="#">emarketer.com</a> survey found that 63% of consumers were <strong>more likely to return to a website that offers live chat</strong>, and 62% reported being <strong>more likely to purchase</strong> from the site again.
			</p>
		</li>
	</ul>
	<!--/ horizontal boxes -->
	<p>
		We deliver business that you'd otherwise be continuing to lose each month to your competition – and the best part is our service pays for itself quickly. For some businesses, the <strong>ROI is well over 500%!</strong> The LeadsChat software includes a web-based ROI calculator for you to measure your own return. The numbers don't lie! We want you to experience the system for yourself and see just how LeadsChat can build your business. Yes, that's really 500% – and our <strong>trial period is FREE with no credit card required.</strong>
	</p>
	<p>
		<a href="#"><u>Click here now</u></a> to contact us!
	</p>
</div>
<!--/ text content -->