<div class="bodywrap">

	<div class="container">

    	
		
	<?php echo $this->partial('include/index/header.phtml')?>

	

	<!-- middle -->

		<div class="middle">





			<!-- content -->

			<div class="wrapper">

				<div class="content">



					<!-- text content -->

					<div class="text">



						<h1 class="blue">Got something to say? Please drop us a line</h1>



						<p>Drop us a line and we will get back to you in 2 Business days.</p>



						<p>
							We look forward to hearing feedback from our clients. <br />

							Please let us know if we can be of any assistance and we’d be
							happy to help.
						</p>





						<div class="contact-form">



							<form action="" method="post" class="ajax_form"
								enctype="multipart/form-data">

								<input type="hidden" id="temp_url" name="temp_url"
									value="http://www.themefuse.com/demo/html/C3" /> <input
									type="hidden" id="tempcode" name="tempcode"
									value="c3VwcG9ydEB0aGVtZWZ1c2UuY29t" /> <input type="hidden"
									id="myblogname" name="myblogname" value="C3" />

								<p class="inputtext">
									<label>Name *</label> <input name="yourname" id="name" value=""
										size="40" type="text" class="required" />
								</p>

								<p class="inputtext">
									<label>Email *</label> <input name="email" id="email" value=""
										class="inputtext" size="40" type="text" class="required" />
								</p>

								<p class="inputtext">
									<label>Company</label> <input name="company" id="company"
										value="" class="inputtext" size="40" type="text" />
								</p>

								<p class="inputtext">
									<label>Country</label> <input name="country" id="country"
										value="" class="inputtext" size="40" type="text" />
								</p>

								<div class="clear"></div>

								<p class="textarea">
									<label>Message *</label>
									<textarea name="message" id="message" cols="40" rows="10"
										class="required"></textarea>
								</p>

								<p class="btn-send text-right">

									<span class="notice-field"><em><strong>* mandatory fileds</strong></em></span>

									<input value="Send Message" id="send" type="submit" />



								</p>

							</form>

							<div class="clear"></div>



						</div>





					</div>

					<!--/ text content -->



				</div>

			</div>



			<!--/ content -->        




		<?php echo $this->partial('include/index/content-navigation.phtml')?>
        

        <div class="clear"></div>

		</div>

		<!--/ middle -->





	</div>

	<!--/ container -->    

	<?php echo $this->partial('include/index/footer.phtml')?>
</div>
<?php echo $this->partial("include/index/tracker.phtml")?>
