<!-- top box-->
<div class="topbox">
	<div class="topbox-image"><img src="/images/img-1.png" alt="" width="483" height="325" border="0" />
	</div>
	<div class="topbox-right">
		<div class="topbox-text">
			<div class="topbox-title">
				<strong>Introduction</strong>
			</div>
			<p>
				LeadsChat is a cloud-based business communication and management software solution for the 21st century.
			</p>
		</div>
		<p>
			<a href="#" class="btn-video">Watch Video</a>
		</p>
	</div>
	<div class="clear"></div>
</div>
<!--/ top box-->
<!-- text content -->
<div class="text">
	<h1>Sign-Up and Implementation In Three Easy Steps:  </h1>
	<p class="text-big"></p>
	<!-- horizontal boxes -->
	<div class="horizontal-box">
		<div class="horizontal-image"><img src="/images/tmp_image_1.gif" width="90" height="80" alt="" />
		</div>
		<h2>Sign up first!</h2>
		<p>
			First, there’s a <strong>5-minute sign-up form</strong> you'll fill out to begin your 24-hour free trial.
		</p>
		<div class="clear"></div>
	</div>
	<div class="horizontal-box">
		<div class="horizontal-image"><img src="/images/tmp_image_2.gif" width="90" height="80" alt="" />
		</div>
		<h2>Review Your Information</h2>
		<p>
			After reviewing your information and learning more about your business, one of our Implementation Specialists contacts you to provide you with your username and password and to walk you through the entire system. We’ll also get the free live chat software set up on your website via your dashboard plug-in. <strong>For most businesses, free trial activation takes place on the same day.</strong>
		</p>
		<div class="clear"></div>
	</div>
	<div class="horizontal-box">
		<div class="horizontal-image"><img src="/images/tmp_image_2.gif" width="90" height="80" alt="" />
		</div>
		<h2>Our Recommendation</h2>
		<p>
			If you plan on activating User Groups on your Dashboard, please inform your Implementation Specialist that you’d like to do a web-based conference call to include your team. (We are happy to set this up free of charge).
		</p>
		<div class="clear"></div>
	</div>
	<!--/ horizontal boxes -->
	<!-- vertical boxes -->
	<div class="white-box">
		<div class="vertical-box" style="width:658px;">
			<h2>After your free trial period..</h2>
			<p>
				You can <u>select from our Bulk Leads packages</u><a href="#"> [click here for pricing options]</a>
			</p>
			<p>
				One of our goals is to help your business make money during your free trial and we’re ready to help you get started. Don't go another day letting business and money flow out your front door!
			</p>
			<p>
				<a href="#"><u>Click here</u></a> to sign up for <strong>our free 24-hour trial</strong> now – there's no obligation and <strong>no credit card required!</strong>
			</p>
		</div>
		<div class="white-box-bot"></div>
	</div>
	<!--/ vertical boxes -->
</div>
<!--/ text content -->
