<div class="bodywrap homepage">

	<div class="container">
		<?php echo $this->partial('include/index/header.phtml')?>
		<!-- top-slider -->
		<div id="topslider" class="tabs-bottom">

			<ul>

				<li class="first"><a href="#fragment-1" class="ico-1"><span><b>Flexible</b>
							Marketing</span></a></li>

				<li><a href="#fragment-2" class="ico-2"><span><b>Improved</b>
							eCommerce</span></a></li>

				<li><a href="#fragment-3" class="ico-3"><span><b>Software</b> as a
							Service</span></a></li>

				<li><a href="#fragment-4" class="ico-4"><span><b>Powerfull</b>
							analytics</span></a></li>

			</ul>



			<div id="fragment-1">

				<div class="left-text">

					<span class="slide-title"><strong>At <span>C3</span> we are very
							serious about business solutions
					</strong></span> <a href="#"><img src="images/btn_plus.gif" alt=""
						width="41" height="41" border="0" class="btn-plus" /></a>

					<p>C3 is the SaaS platform built from scracth for Online Business.
						By replacing 3+ essential business tools with one integrated
						online platform, you can build exactly what your clients need sed
						do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>

				</div>

				<div class="right-text">
					<a href="#"><img src="images/img-1.png" alt="" width="483"
						height="325" border="0" /></a>

				</div>

				<div class="clear"></div>

			</div>



			<div id="fragment-2">

				<div class="left-text">

					<span class="slide-title"><strong>At <span>C3</span> we are very
							serious about Improved eCommerce
					</strong></span> <a href="#"><img src="images/btn_plus.gif" alt=""
						width="41" height="41" border="0" class="btn-plus" /></a>

					<p>"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed
						do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
						enim ad minim veniam, quis nostrud exercitation ullamco laboris
						nisi ut aliquip ex ea commodo consequat.</p>

				</div>

				<div class="right-text">
					<a href="#"><img src="images/img-2.png" alt="" width="483"
						height="325" border="0" /></a>

				</div>

				<div class="clear"></div>

			</div>



			<div id="fragment-3">

				<div class="left-text">

					<span class="slide-title"><strong><span>Software as a Service</span>
							is the coolest kid in town</strong></span> <a href="#"><img
						src="images/btn_plus.gif" alt="" width="41" height="41" border="0"
						class="btn-plus" /></a>

					<p>C3 is the SaaS platform built from scracth for Online Business.
						By replacing 3+ essential business tools with one integrated
						online platform, you can build exactly what your clients need...
						C3 is the SaaS platform built from scracth for Online Business.</p>

				</div>

				<div class="right-text">
					<img src="images/img-4.png" alt="" width="483" height="325"
						border="0" />

				</div>

				<div class="clear"></div>

			</div>



			<div id="fragment-4">

				<div class="left-text">

					<span class="slide-title"><strong>At <span>C3</span> we provide top
							notch design and analytics tools
					</strong> </span> <a href="#"><img src="images/btn_plus.gif" alt=""
						width="41" height="41" border="0" class="btn-plus" /></a>

					<p>"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed
						do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
						enim ad minim veniam, quis nostrud exercitation ullamco laboris
						nisi ut aliquip ex ea commodo consequat.</p>

				</div>

				<div class="right-text">

					<img src="images/img-3.png" width="483" height="325" alt="" />

				</div>

				<div class="clear"></div>

			</div>



			<div class="clear"></div>

		</div>

		<!-- top-slider -->



		<!-- middle -->

		<div class="middle">





			<!-- content -->

			<div class="wrapper">

				<div class="content">



					<!-- top baner-->

					<div class="upper-title">WHY USE OUR ONLINE SERVICES?</div>

					<h1>
						Easy access to our software from anywhere <br />even from your
						pocket
					</h1>



					<div class="mobile-box">

						<div class="box-text">

							<p>
								Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
								eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
								enim ad minim veniam. Excepteur sint occaecat cupidatat non
								proident. Lorem ipsum dolor sit amet, consectetur adipisicing
								elit <br />
								<a href="#"><img src="images/btn_plus_white.gif" alt=""
									width="35" height="35" border="0" class="alignright" /></a>
								Duis aute irure dolor in reprehenderit in voluptate.
							</p>

						</div>

					</div>



					<!--/ top baner-->



					<!-- two-columns -->

					<div class="two-columns">

						<div class="col-1">

							<h2>LATEST NEWS AND INFO</h2>

							<h3>
								<a href="#">Technical Support just got better!</a>
							</h3>

							<div class="short-entry">

								<p>There's a voice that keeps on calling me. Down the road,
									that's where I'll always be. Every stop I make, I make a new
									friend. Can't stay for long, just turn around and I'm gone
									again. Maybe tomorrow, I'll want to settle down</p>

							</div>

							<ul>

								<li><a href="#">Connect to Remote Support</a></li>

								<li><a href="#">Via telephone: 800.898.3838</a></li>

								<li><a href="#">Troubleshooting F.A.Q.</a></li>

							</ul>



						</div>



						<div class="gutter"></div>



						<div class="col-1">

							<h2>WANT TO LEARN MORE?</h2>

							<h3>
								<a href="#">Full comparison of our plans</a>
							</h3>

							<div class="short-entry">

								<p>One for all and all for one, Muskehounds are always ready.
									One for all and all for one, helping everybody. One for all and
									all for one, it's a pretty story. Sharing everything with fun,
									that's the way to be. One for all and all for one</p>

							</div>

							<ul class="list-icons">

								<li class="ico-pdf"><a href="#">Download the PDF file</a></li>

								<li class="ico-arr"><a href="#">Sign up for a plan</a></li>

							</ul>

						</div>



						<div class="clear"></div>

					</div>

					<!--/ two-columns -->





				</div>

			</div>



			<!--/ content -->



			<!-- navigation -->

			<div class="navigation">



				<div class="login">

					<a href="/owners/register"><img src="images/btn-signup.gif"
						alt="Free Sign Up" width="175" height="55" border="0" /></a><a
						href="#"><img src="images/btn-plans.gif" alt="Plans and Pricing"
						width="135" height="55" border="0" /></a>

					<p>
						Already registered? Then just <a href="/owners/login">Sign In</a>
					</p>

				</div>



				<div class="testimonials">

					<h3>What the people say?</h3>



					<p class="quote">"Great, great changes to an already amazingly good
						software from C3. Thanks for making this so much more amazing"</p>

					<p class="author">
						<strong>Jonathan Doe, CEO Company Name</strong>
					</p>



					<a href="#" class="btn-more">view more</a>

				</div>



				<div class="recent-posts">

					<div class="recent-posts-top"></div>

					<div class="space">

						<h3>Recent Blog Posts</h3>

						<ul>

							<li><a href="#">Lorem ipsum dolor sit amet, consectetur</a>

								<div class="author">
									Steave Barnst <span>14-Feb-2010</span>
								</div></li>



							<li><a href="#">One for all and all for one</a>

								<div class="author">
									Merlyn Johnes <span>14-Feb-2010</span>
								</div></li>



							<li><a href="#">Technical Support just got better!</a>

								<div class="author">
									Mike Mayers <span>14-Feb-2010</span>
								</div></li>



							<li><a href="#">Lorem ipsum dolor sit amet</a>

								<div class="author">
									C3Admin <span>14-Feb-2010</span>
								</div></li>

						</ul>

					</div>

				</div>



				<div class="clear"></div>



			</div>

			<!--/ navigation -->



			<div class="clear"></div>

		</div>

		<!--/ middle -->





	</div>

	<!--/ container -->

	<?php echo $this->partial('include/index/footer.phtml')?>
</div>

<?php echo $this->partial("include/index/tracker.phtml")?>
