<div class="bodywrap homepage">

	<div class="container">
		<?php echo $this->partial('include/index/header.phtml')?>
		<!-- top-slider -->
		 <div id="topslider" class="tabs-bottom">

        	<ul>

                <li class="first"><a href="#fragment-1" class="ico-1"><span><b>Latest</b> Technology</span></a></li>

                <li><a href="#fragment-2" class="ico-4"><span><b>Convert</b> More Visitors</span></a></li>

                <li><a href="#fragment-3" class="ico-2"><span><b>Fast</b> Implementation</span></a></li>

                <li><a href="#fragment-4" class="ico-3"><span><b>Live</b> Chat</span></a></li>

            </ul>

			

            <div id="fragment-1">

            	<div class="left-text">

                    <span class="slide-title"><strong>Let <span>LeadsChat</span> Cloud Technology Accelerate Your Business</strong></span>	

                    <a href="#"><img src="images/btn_plus.gif" alt="" width="41" height="41" border="0" class="btn-plus" /></a>

<p>LeadsChat is a cloud-based business communication and management software solution for the 21st century. It's lightning fast, easy-to-use, inexpensive, and pays for itself quickly with a high return on investment (ROI).</p>

              </div>

                <div class="right-text"> <a href="#"><img src="images/img-1.png" alt="" width="483" height="325" border="0" /></a>

                </div>

                <div class="clear"></div>

          	</div>

            

            <div id="fragment-2">

            	<div class="left-text">

            	<span class="slide-title"><strong>You Only <span>Pay</span> for Solid Leads</strong></span>

                <a href="#"><img src="images/btn_plus.gif" alt="" width="41" height="41" border="0" class="btn-plus" /></a>

				<p>With LeadsChat, we help convert website visitors into profits in a cost-effective pay-for-lead model, which means <strong>you only pay for highly qualified leads.</strong> Our job is to deliver high-quality leads in a cost-effective way to help you grow your business. Leverage our technology and management expertise to help accelerate your business! Click here to learn more.
</p>

                </div>

                <div class="right-text"> <a href="#"><img src="images/img-2.png" alt="" width="483" height="325" border="0" /></a>

                </div>

                <div class="clear"></div>

            </div>



            <div id="fragment-3">

               <div class="left-text">

                    <span class="slide-title"><strong><span>Get Started Now</span> and Get More Leads</strong></span>

                    <a href="#"><img src="images/btn_plus.gif" alt="" width="41" height="41" border="0" class="btn-plus" /></a>

                    <p>We offer multiple subscriber options at different price levels, so you can choose the best match for your business. Set-up is a quick and easy three-step process – and for most businesses, <strong>activation and lead generation begin on the same day.</strong></strong></p>

              </div>

                <div class="right-text"> <img src="images/img-4.png" alt="" width="483" height="325" border="0" />

                </div>

                <div class="clear"></div>

            </div>

            

            <div id="fragment-4">

                <div class="left-text">

            	<span class="slide-title"><strong>Why Is Offering <span>Live Chat</span>  Important?</strong> </span>

                <a href="#"><img src="images/btn_plus.gif" alt="" width="41" height="41" border="0" class="btn-plus" /></a>

				<p>Did you know that on some days, up to 90% of your website visitors leave without contacting you? Without live chat assistance available to answer questions and gather information, <strong>you're losing those leads</strong> – and the money they're willing to spend on your products or services. LeadsChat <strong>casts a wide net</strong> and only sends you what is potentially profitable. You never pay for hardware, software, or labor.</p>

                </div>

                <div class="right-text">

                	<img src="images/img-3.png" width="483" height="325" alt="" />

                </div>

                <div class="clear"></div>

            </div>

	

    		<div class="clear"></div>

        </div>

        <!-- top-slider --> 

	

	<!-- middle -->

	<div class="middle">

    



	<!-- content -->     

        <div class="wrapper">

          <div class="content">

            

			<!-- top baner-->

            <div class="upper-title">WHY USE OUR ONLINE SERVICES?</div>

            <h1>Access From Anywhere </h1>

                

              <div class="mobile-box">

           	    <div class="box-text">

  <p>LeadsChat's robust features are coupled with unparalleled integration capabilities, so you won't miss a single lead when you're out of the office. <strong>Access your information anywhere</strong> – on your tablet PC, via our FREE smartphone app, or online via our website.<a href="#"><img src="images/btn_plus_white.gif" alt="" width="35" height="35" border="0" class="alignright" /></a> </p>

                    </div>

              </div>

              

			<!--/ top baner-->   

            

            <!-- two-columns -->

            <div class="two-columns">

                <div class="col-1">

                	<!--<h2>LATEST NEWS AND INFO</h2>-->

                    <h3><a href="#">Don't Leave Money on the Table</a></h3>

					<div class="short-entry">

                        <p>Let's face it: No matter what industry you're in, if you don't have leads in your pipeline, you don't have business. LeadsChat helps uncover an <strong>untapped profit source</strong> your business isn't capitalizing on: the live, eager customers that are on your website every day. We make it easy for you to answer their questions, get their contact information, and turn visitors into sales and service appointments. <!--<a href="#">Click here to learn more</a></p>-->

                    </div>	

                    <ul>

                    	<li><a href="how-it-works.html">Click here to learn more</a></li>

                        <!--<li><a href="#">Via telephone: 800.898.3838</a></li>

                        <li><a href="#">Troubleshooting F.A.Q.</a></li>-->

                    </ul>

                   

                </div>

                

                <div class="gutter"></div>

                

                <div class="col-1">

                	<!--<h2>WANT TO LEARN MORE?</h2>-->

                    <h3><a href="#">Free 24-Hour Trial</a></h3>

					<div class="short-entry">
We're so confident that LeadsChat will transform your sales process and increase your profits that we'll give you a <strong>free 24-hour trial</strong> with unlimited leads – there's no obligation and <strong>no credit card required!</strong> (Did we mention it's free?)<!--<a href="#">Click here to sign up!</a>--> </p>

                    </div>	

                    <ul class="list-icons">

                    <!--	<li class="ico-pdf"><a href="#">Download the PDF file</a></li>-->

                        <li class="ico-arr"><a href="#">Click here to sign up!</a></li>

                    </ul>

                </div>

                

            	<div class="clear"></div>

            </div>

            <!--/ two-columns -->

              

                

            </div>

        </div>

        

<!--/ content -->        



<!-- navigation -->        

        <div class="navigation"> 

       	

            <div class="login">

                <a href="/owners/register"><img src="images/btn-signup.gif" alt="Free Sign Up" width="175" height="55" border="0" /></a><a href="#"><img src="images/btn-plans.gif" alt="Plans and Pricing" width="135" height="55" border="0" /></a>

                <p>Already registered? Then just <a href="/owners/login">Sign In</a></p>

            </div>

            

            <div class="testimonials">

            	<h3>What the people say?</h3>

                

                <p class="quote">"Great, great changes to an already amazingly good software from C3. Thanks for making this so much more amazing"</p>

                <p class="author"><strong>Jonathan Doe, CEO Company Name</strong></p>

                

                <a href="#" class="btn-more">view more</a>

            </div>

            

            <div class="recent-posts">

            	<div class="recent-posts-top"></div>

                <div class="space">

            	<h3>Recent Blog Posts</h3>

            	<ul>

                	<li>

                    <a href="#">Lorem ipsum dolor sit amet, consectetur</a>

					<div class="author">Steave Barnst <span>14-Feb-2010</span></div>

                    </li>

                    

                    <li>

                    <a href="#">One for all and all for one</a>

					<div class="author">Merlyn Johnes <span>14-Feb-2010</span></div>

                    </li>

                    

                    <li>

                    <a href="#">Technical Support just got better!</a>

					<div class="author">Mike Mayers <span>14-Feb-2010</span></div>

                    </li>

                    

                    <li>

                    <a href="#">Lorem ipsum dolor sit amet</a>

					<div class="author">C3Admin <span>14-Feb-2010</span></div>

                    </li>

                </ul>

                </div>

            </div>

            

            <div class="clear"></div>

        

        </div>

<!--/ navigation -->

        

        <div class="clear"></div>

    </div>

    <!--/ middle -->



            

    </div>

<!--/ container -->    
		

	<?php echo $this->partial('include/index/footer.phtml')?>
</div>

<?php echo $this->partial("include/index/tracker.phtml")?>
