<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<title>Homepage</title>

<link rel="stylesheet" type="text/css" href="css/stylesheet.css" />

<script type="text/javascript" src="js/jquery-1.7.1.min.js"></script>



<!-- topslider -->

<link rel="stylesheet" href="css/ui.tabs.css" type="text/css" media="print, projection, screen" />

<script type="text/javascript" src="js/ui.core.js"></script>

<script type="text/javascript" src="js/ui.tabs.js"></script>

<script type="text/javascript">

	$(function() {

		$('#topslider').tabs({ fx: [{opacity:'toggle', duration:'fast'},{opacity:'toggle', duration:'fast'}] }).tabs('rotate', 4000);

	});

</script>

<!--/ topslider -->

<link rel="stylesheet" type="text/css" href="css/custom.css" />
</head>



<body>







<div class="bodywrap homepage">

	<div class="container">

    	

        <!-- header -->

   	  <div class="header">

        	<div class="logo"><a href="#"><img src="images/logo.png" alt="C3 Clean Glassy Corporate" border="0" /></a></div>

            

            <div class="topmenu">

            	<ul>

                	<li><a href="/" class="active"><span>Home</span></a></li>

                    <li><a href="take-tour.html"><span>Take the Tour</span></a></li>

                    <li><a href="pricing.html"><span>Pricing</span></a></li>

                    <li><a href="work.html"><span>Work</span></a></li>

               		<li><a href="about.html"><span>About</span></a></li>

                    <li><a href="contact.html"><span>Contact</span></a></li>

                    <li class="last"><a href="blog.html"><span>Blog</span></a></li>

                </ul>

                <div class="clear"></div>

            </div>

        </div>

   		<!--/ header -->  

        

        <!-- top-slider -->   



        <div id="topslider" class="tabs-bottom">

        	<ul>

                <li class="first"><a href="#fragment-1" class="ico-1"><span><b>Flexible</b> Marketing</span></a></li>

                <li><a href="#fragment-2" class="ico-2"><span><b>Improved</b> eCommerce</span></a></li>

                <li><a href="#fragment-3" class="ico-3"><span><b>Software</b> as a Service</span></a></li>

                <li><a href="#fragment-4" class="ico-4"><span><b>Powerfull</b> analytics</span></a></li>

            </ul>

			

            <div id="fragment-1">

            	<div class="left-text">

                    <span class="slide-title"><strong>At <span>C3</span> we are very serious about business solutions</strong></span>

                    <a href="#"><img src="images/btn_plus.gif" alt="" width="41" height="41" border="0" class="btn-plus" /></a>

<p>C3 is the SaaS platform built from scracth for Online Business. By replacing 3+ essential business tools with one integrated online platform, you can build exactly what your clients need sed do eiusmod tempor incididunt ut labore et dolore magna aliqua </p>

              </div>

                <div class="right-text"> <a href="#"><img src="images/img-1.png" alt="" width="483" height="325" border="0" /></a>

                </div>

                <div class="clear"></div>

          	</div>

            

            <div id="fragment-2">

            	<div class="left-text">

            	<span class="slide-title"><strong>At <span>C3</span> we are very serious about Improved eCommerce</strong></span>

                <a href="#"><img src="images/btn_plus.gif" alt="" width="41" height="41" border="0" class="btn-plus" /></a>

				<p>"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>

                </div>

                <div class="right-text"> <a href="#"><img src="images/img-2.png" alt="" width="483" height="325" border="0" /></a>

                </div>

                <div class="clear"></div>

            </div>



            <div id="fragment-3">

               <div class="left-text">

                    <span class="slide-title"><strong><span>Software as a Service</span> is the coolest kid in town</strong></span>

                    <a href="#"><img src="images/btn_plus.gif" alt="" width="41" height="41" border="0" class="btn-plus" /></a>

                    <p>C3 is the SaaS platform built from scracth for Online Business. By replacing 3+ essential business tools with one integrated online platform, you can build exactly what your clients need... C3 is the SaaS platform built from scracth for Online Business.</p>

              </div>

                <div class="right-text"> <img src="images/img-4.png" alt="" width="483" height="325" border="0" />

                </div>

                <div class="clear"></div>

            </div>

            

            <div id="fragment-4">

                <div class="left-text">

            	<span class="slide-title"><strong>At <span>C3</span> we provide top notch design and analytics tools </strong> </span>

                <a href="#"><img src="images/btn_plus.gif" alt="" width="41" height="41" border="0" class="btn-plus" /></a>

				<p>"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>

                </div>

                <div class="right-text">

                	<img src="images/img-3.png" width="483" height="325" alt="" />

                </div>

                <div class="clear"></div>

            </div>

	

    		<div class="clear"></div>

        </div>

        <!-- top-slider --> 

	

	<!-- middle -->

	<div class="middle">

    



	<!-- content -->     

        <div class="wrapper">

          <div class="content">

            

			<!-- top baner-->

            <div class="upper-title">WHY USE OUR ONLINE SERVICES?</div>

            <h1>Easy access to our software from anywhere <br />even from your pocket</h1>

                

              <div class="mobile-box">

           	    <div class="box-text">

  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam. Excepteur sint occaecat cupidatat non proident. Lorem ipsum dolor sit amet, consectetur adipisicing elit <br /><a href="#"><img src="images/btn_plus_white.gif" alt="" width="35" height="35" border="0" class="alignright" /></a> Duis aute irure dolor in reprehenderit in voluptate. </p>

                    </div>

              </div>

              

			<!--/ top baner-->   

            

            <!-- two-columns -->

            <div class="two-columns">

                <div class="col-1">

                	<h2>LATEST NEWS AND INFO</h2>

                    <h3><a href="#">Technical Support just got better!</a></h3>

					<div class="short-entry">

                        <p> There's a voice that keeps on calling me. Down the road, that's where I'll always be. Every stop I make, I make a new friend. Can't stay for long, just turn around and I'm gone again. Maybe tomorrow, I'll want to settle down</p>

                    </div>	

                    <ul>

                    	<li><a href="#">Connect to Remote Support</a></li>

                        <li><a href="#">Via telephone: 800.898.3838</a></li>

                        <li><a href="#">Troubleshooting F.A.Q.</a></li>

                    </ul>

                   

                </div>

                

                <div class="gutter"></div>

                

                <div class="col-1">

                	<h2>WANT TO LEARN MORE?</h2>

                    <h3><a href="#">Full comparison of our plans</a></h3>

					<div class="short-entry">

                        <p>One for all and all for one, Muskehounds are always ready. One for all and all for one, helping everybody. One for all and all for one, it's a pretty story. Sharing everything with fun, that's the way to be. One for all and all for one</p>

                    </div>	

                    <ul class="list-icons">

                    	<li class="ico-pdf"><a href="#">Download the PDF file</a></li>

                        <li class="ico-arr"><a href="#">Sign up for a plan</a></li>

                    </ul>

                </div>

                

            	<div class="clear"></div>

            </div>

            <!--/ two-columns -->

              

                

            </div>

        </div>

        

<!--/ content -->        



<!-- navigation -->        

        <div class="navigation"> 

       	

            <div class="login">

                <a href="/owners/register"><img src="images/btn-signup.gif" alt="Free Sign Up" width="175" height="55" border="0" /></a><a href="#"><img src="images/btn-plans.gif" alt="Plans and Pricing" width="135" height="55" border="0" /></a>

                <p>Already registered? Then just <a href="/owners/login">Sign In</a></p>

            </div>

            

            <div class="testimonials">

            	<h3>What the people say?</h3>

                

                <p class="quote">"Great, great changes to an already amazingly good software from C3. Thanks for making this so much more amazing"</p>

                <p class="author"><strong>Jonathan Doe, CEO Company Name</strong></p>

                

                <a href="#" class="btn-more">view more</a>

            </div>

            

            <div class="recent-posts">

            	<div class="recent-posts-top"></div>

                <div class="space">

            	<h3>Recent Blog Posts</h3>

            	<ul>

                	<li>

                    <a href="#">Lorem ipsum dolor sit amet, consectetur</a>

					<div class="author">Steave Barnst <span>14-Feb-2010</span></div>

                    </li>

                    

                    <li>

                    <a href="#">One for all and all for one</a>

					<div class="author">Merlyn Johnes <span>14-Feb-2010</span></div>

                    </li>

                    

                    <li>

                    <a href="#">Technical Support just got better!</a>

					<div class="author">Mike Mayers <span>14-Feb-2010</span></div>

                    </li>

                    

                    <li>

                    <a href="#">Lorem ipsum dolor sit amet</a>

					<div class="author">C3Admin <span>14-Feb-2010</span></div>

                    </li>

                </ul>

                </div>

            </div>

            

            <div class="clear"></div>

        

        </div>

<!--/ navigation -->

        

        <div class="clear"></div>

    </div>

    <!--/ middle -->



            

    </div>

<!--/ container -->    



	

<!-- footer -->

	<div class="footer">

    	<div class="container">

     		

            <div class="cols fcol-1">

            	<h3>Links</h3>

                <ul>

                	<li><a href="/">Homepage</a></li>

                    <li><a href="#">Take the Tour</a></li>

                    <li><a href="#">Plans &amp; Pricing</a></li>

                    <li><a href="#">About us</a></li>

                </ul>

            </div>

            

            <div class="cols fcol-2">

            	<h3>Our Products</h3>

                <ul>

                	<li><a href="#">Basecramp</a></li>

                    <li><a href="#">Analytics Groove</a></li>

                    <li><a href="#">VideoMate</a></li>  

                </ul>

            </div>

            

            <div class="cols fcol-3">

            	<h3>Support</h3>

                <ul>

                	<li><a href="#">F.A.Q.</a></li>

                    <li><a href="#">Live IM chat</a></li>

                    <li><a href="#">Forums</a></li>  

                    <li><a href="#">Contribute</a></li>

                </ul>

            </div>

            

            <div class="cols fcol-4">

            	<h3>Get in touch</h3>

                <ul>

                	<li><a href="#">Feedback</a></li>

                    <li><a href="#">Contact</a></li>

                    <li><a href="#">Business inquiry</a></li>

                    <li><a href="#">Partnership</a></li>

                </ul>

            </div>

            

			<div class="cols fcol-5">

           	<h3>Follow us on</h3>



                <div class="icons-fallow">

                <a href="#"><img src="images/icon-facebook.gif" alt="Fallow us on Facebook" width="93" height="35" border="0" /></a> <a href="#"><img src="images/icon-twitter.gif" alt="allow us on Twitter" width="40" height="39" border="0" /></a>

                </div>

                

                <div class="copyright">

                    <p>Copyright  &copy;  2010 C3 Business <br />

                    All the respective rights reserved</p>

                </div>

                

			</div>

            

               

        </div>

    </div>

<!--/ footer -->

    

</div>



<script type="text/javascript">

var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");

document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));

</script>

<script type="text/javascript">

try {

var pageTracker = _gat._getTracker("UA-15832274-1");

pageTracker._trackPageview();

} catch(err) {}</script>



<script type="text/javascript">

var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");

document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));

</script>

<script type="text/javascript">

try {

var pageTracker = _gat._getTracker("UA-15832274-4");

pageTracker._trackPageview();

} catch(err) {}</script>

</body>

</html>

