
<div class="bodywrap onecolumn">

	<div class="container">
		<?php echo $this->partial("include/index/header.phtml")?>

		<!-- middle -->

		<div class="middle">





			<!-- pricing boxes -->

			<div class="price-columns">



				<div class="col-1">



					<div class="black-box">

						<div class="black-box-title">
							<h2>Start-up</h2>
						</div>

						<div class="black-box-content">

							<div class="black-box-intro">Ideal for small antrepreneurs</div>

							<div class="black-box-list" id="features1">

								<ul>

									<li class="active">Lorem ipsum dolor sit amet</li>

									<li class="active">Ut enim ad minim veniam</li>

									<li class="notactive">Excepteur sint occaecat</li>

									<li class="notactive">Duis aute irure dolor in reprehenderit</li>

									<li class="notactive">Eiusmod tempor incididunt</li>

								</ul>

							</div>

							<div class="black-box-more">
								<a href="#">Find out more</a>
							</div>

						</div>

					</div>



					<div class="icon-box ico-signup">

						<div class="icon-img">
							<a href="#"><img src="images/ico-free.gif" alt="" width="69"
								height="78" border="0" /></a>
						</div>

						<h3>
							<a href="#">Sign Up for Free</a>
						</h3>

						<span>learn more about how it works</span>

					</div>



				</div>



				<div class="col-1">

					<div class="black-box">

						<div class="black-box-title">
							<h2>Update</h2>
						</div>

						<div class="black-box-content">

							<div class="black-box-intro">Perfectly adapted for medium
								businesses</div>

							<div class="black-box-list" id="features2">

								<ul>

									<li class="active">Lorem ipsum dolor sit amet</li>

									<li class="active">Ut enim ad minim veniam</li>

									<li class="active">Excepteur sint occaecat</li>

									<li class="notactive">Duis aute irure dolor in reprehenderit</li>

									<li class="notactive">Eiusmod tempor incididunt</li>

								</ul>

							</div>

							<div class="black-box-more">
								<a href="#">Find out more</a>
							</div>

						</div>

					</div>



					<div class="icon-box">

						<div class="icon-img">
							<a href="#"><img src="images/ico-purchase-2.gif" alt=""
								width="69" height="78" border="0" /></a>
						</div>

						<h3>
							<a href="#">Purchase Now</a>
						</h3>

						<span>Still not sure? try the Demo</span>

					</div>



				</div>



				<div class="col-1">

					<div class="black-box">

						<div class="black-box-title">
							<h2>Premium</h2>
						</div>

						<div class="black-box-content">

							<div class="black-box-intro">Best thing since sliced bread</div>

							<div class="black-box-list" id="features3">

								<ul>

									<li class="active">Lorem ipsum dolor sit amet</li>

									<li class="active">Ut enim ad minim veniam</li>

									<li class="active">Excepteur sint occaecat</li>

									<li class="active">Duis aute irure dolor in reprehenderit</li>

									<li class="active">Eiusmod tempor incididunt</li>

								</ul>

							</div>

							<div class="black-box-more">
								<a href="#">Find out more</a>
							</div>

						</div>

					</div>



					<div class="icon-box">

						<div class="icon-img">
							<a href="#"><img src="images/ico-purchase-3.gif" alt=""
								width="69" height="78" border="0" /></a>
						</div>

						<h3>
							<a href="#">Purchase Now</a>
						</h3>

						<span>Save 50% on 1 year subscription</span>

					</div>



				</div>



				<script type="text/javascript">

		$("#features1 li:even").addClass("even");

		$("#features2 li:even").addClass("even");

		$("#features3 li:even").addClass("even");

        </script>

				<div class="clear"></div>

			</div>

			<!--/ pricing boxes -->





			<!-- vertical boxes -->

			<div class="white-box2">

				<div class="col-2">

					<h2>Helping you get the best results</h2>

					<p>Straight'nin' the curve, flat'nin' the hills. Someday the
						mountain might get 'em, but the law never will. Makin' their way,
						the only way they know how, that's just a little bit more than the
						law will allow.</p>

				</div>



				<div class="col-2">

					<img src="images/tmp_image_1.gif" width="90" height="80" alt=""
						class="alignright" />

					<h2>30 days Free, no registration required</h2>

					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
						eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>

				</div>



				<div class="white-box2-bot"></div>

			</div>

			<!--/ vertical boxes -->





			<div class="clear"></div>

		</div>

		<!--/ middle -->





	</div>

	<!--/ container -->

	<?php echo $this->partial("include/index/footer.phtml")?>
</div>
<?php echo $this->partial("include/index/tracker.phtml")?>

