<!-- text content -->
<div class="text">
	<h1>Why Choose LeadChat?</h1>
	<p class="text-big"></p>
	<!-- vertical boxes -->
	<div class="white-box">
		<div class="vertical-box" style="width:658px;">
			<h2>Pay-Per-Lead Model with Free Staffing and Software</h2>
			<p>
				There are hundreds of online companies offering live chat support software and/or outsourcing services -- but with LeadsChat, our business approach is entirely different. LeadsChat provides free cloud-based software; we staff the online chat for you with highly-trained sales agents at no extra labor cost; we provide a free smartphone app; and we only send you high-quality leads in a free web-based information management system. Our pay-per-lead modeling means that you don't have to spend money staffing anyone to do live chat for you – we do that – and the software is always free. <strong>You pay on a per-lead basis ONLY</strong>, selecting from one of our Bulk Leads packages.
			</p>
		</div>
		<div class="white-box-bot"></div>
	</div>
	<!--/ vertical boxes -->
	<p>
		Our LeadsChat Live Support agents are seasoned sales professionals who actively engage with website visitors. We carefully identify and qualify site the visitors who are profitable. The ROI can be astounding: Just one lead for an electrician can be worth a $600 light fixture job, and just one lead for a plumber can turn into a $350 pipe reduction job. And once your foot is in the door with that new customer, you can turn that sale into even more profit down the road through additional business, referrals and more.
	</p>
	<p>
		Smart business owners see the value of LeadsChat and are using our service to immediately increase revenue and grow their business.  Again, <strong>we only deliver you highly-qualified leads – ONLY</strong> people who have stated they are VERY interested in your product or service.
	</p>
	<p>
		Why continue to let your competition pick over customers who came to your website first? Get LeadsChat now!
	</p>
	<p>
		<a href="#">Click here</a> to sign up for our <strong>free 24-hour trial!</strong>
	</p>
</div>
<!--/ text content -->