<div>
	<div id="chat-container">
		<div id="chat-list">
			<div class="chat-item">
				<div class="content">
				Looking for an available agent...
				</div>				
			</div>
		</div>
		<div id="livechat">
			<div id="secure-pic">
				<h1><img src="<?php echo $this->baseUrl?>/images/lock.png"/><span>Live Chat</span></h1>
				<img src="<?php echo $this->baseUrl?>/images/agent.png"/>
			</div>
		</div>
		<div id="chat-messenger">
			<form id="chat-form" method="POST">
				<textarea id="message-text" name="message" placeholder="Type a message"></textarea>
				<input type="hidden" value="<?php echo $this->website?>" name="website" id="website"/>	
				<input type="hidden" id="from_id" name="from_id" value="<?php echo $this->visitor_id?>"/>
				<input type="hidden" id="from_type" name="from_type" value="V"/>
				<input type="hidden" id="chat_session_id" name="chat_session_id" value="-1"/>
				<button id="send-chat" type="submit">Send</button>
			</form>
		</div>
	</div>
</div>