<footer class="footer container-fluid" role="contentinfo">
	<div class="row-fluid">
		<div class="span5">
			<img src="/images/owners/register/logo-small.png" alt="Leadschat.com"/>&nbsp;<a href="#">TERMS OF SERVICE</a> | <a href="#">PRIVATE POLICY</a>
		</div>
		<div class="span5 copyright">
			COPYRIGHT © 2012 LEADS CHAT IS A PRODUCT OF LEADS CHAT, LLC. ALL RIGHTS RESERVED
		</div>
		<div class="span2 right">
			<a href="#"><img src="/images/owners/register/fb.png"/></a>
			<a href="#"><img src="/images/owners/register/twitter.png"/></a>
			<a href="#"><img src="/images/owners/register/plus.png"/></a>
			<a href="#"><img src="/images/owners/register/rss.png"/></a>
			<a href="#"><img src="/images/owners/register/fb.png"/></a>
		</div>
	</div>
</footer>