<header class="header">
	<div class="container">
		<nav class="navigation">
			<div class="navigation-main">
				<ul>
					<li>
						<a href="#">Home</a>
					</li>
					<li>
						<a href="#">How it works</a>
					</li>
					<li>
						<a href="#">Service</a>
					</li>
					<li>
						<a href="#">Pricing</a>
					</li>
					<li class="last">
						<a href="#">Contact Us</a>
					</li>
				</ul>
			</div>
			<div class="contact-number"><img src="/images/owners/register/phone.png" alt="Call us at Leadschat +1-818-538-6279"/> +1-818-538-6279
			</div>
		</nav>
		<div class="logo span4"><img src="/images/owners/register/logo.png" alt="Leadschat.com"/>
		</div>
	</div>
</header>
<div class="divider"></div>