
<!-- navigation -->

<div class="navigation">





	<div class="left-menu">

		<ul>

			<li class="active"><a href="/owners/about">About the Company</a></li>

			<li><a href="#">Meet our Team</a></li>

			<li><a href="#">How we do things</a></li>

			<li><a href="#">Join the Team</a></li>

		</ul>

	</div>





	<p>
		<a href="/owners/register"><img src="<?php echo $this->baseUrl()?>/images/btn-view-sites.gif"
			alt="View our websites" width="179" height="40" border="0" /></a>
	</p>

	<p>
		<a href="#"><img src="<?php echo $this->baseUrl()?>/images/btn-our-products.gif"
			alt="Our Products" width="179" height="40" border="0" /></a>
	</p>





</div>

<!--/ navigation -->