<!-- navigation -->
<div class="navigation">
	<div class="left-menu">
		<ul>
			<li class="active">
				<a href="/index/about">About the Company</a>
			</li>
		</ul>
	</div>
	<p>
		<a href="/owners/register"><img src="/images/btn-free-signup.gif" alt="Free Sign Up" width="179" height="40" border="0" /></a>
	</p>
	<p>
		<a href="/index/pricing"><img src="/images/btn-pricing.gif" alt="Plans and Pricing" width="179" height="40" border="0" /></a>
	</p>
</div>
<!--/ navigation -->