<!-- footer -->

<div class="footer">

	<div class="container">



		<div class="cols fcol-1">

			<h3>Links</h3>

			<ul>

				<li><a href="/">Homepage</a></li>

				<li><a href="#">Take the Tour</a></li>

				<li><a href="/index/pricing">Plans &amp; Pricing</a></li>

				<li><a href="/index/about">About us</a></li>

			</ul>

		</div>



		<div class="cols fcol-2">

			<h3>Our Products</h3>

			<ul>

				<li><a href="#">Basecramp</a></li>

				<li><a href="#">Analytics Groove</a></li>

				<li><a href="#">VideoMate</a></li>

			</ul>

		</div>



		<div class="cols fcol-3">

			<h3>Support</h3>

			<ul>

				<li><a href="#">F.A.Q.</a></li>

				<li><a href="#">Live IM chat</a></li>

				<li><a href="#">Forums</a></li>

				<li><a href="#">Contribute</a></li>

			</ul>

		</div>



		<div class="cols fcol-4">

			<h3>Get in touch</h3>

			<ul>

				<li><a href="#">Feedback</a></li>

				<li><a href="#">Contact</a></li>

				<li><a href="#">Business inquiry</a></li>

				<li><a href="#">Partnership</a></li>

			</ul>

		</div>



		<div class="cols fcol-5">

			<h3>Follow us on</h3>



			<div class="icons-fallow">

				<a href="#"><img src="<?php echo $this->baseUrl()?>/images/icon-facebook.gif"
					alt="Fallow us on Facebook" width="93" height="35" border="0" /></a>
				<a href="#"><img src="<?php echo $this->baseUrl()?>/images/icon-twitter.gif"
					alt="allow us on Twitter" width="40" height="39" border="0" /></a>

			</div>



			<div class="copyright">

				<p>
					Copyright &copy; 2010 C3 Business <br /> All the respective rights
					reserved
				</p>

			</div>



		</div>





	</div>

</div>

<!--/ footer -->