<?php 
	echo $this->actionName;
	if ($this->actionName=="index"){
		$index = "class='active'";
	}else{
		$index = "";
	}
	
	if ($this->actionName=="about"){
		$about = "class='about'";
	}else{
		$about = "";
	}
	

?>

<!-- header -->
<div class="header">
	<div class="logo">
		<a href="/"><img src="<?php echo $this->baseUrl()?>/images/logo.png" alt="C3 Clean Glassy Corporate"
			border="0" /></a>
	</div>
	<div class="topmenu">
		<ul>
			<li><a href="/" <?php echo $index?>><span>Home</span></a></li>
			<li><a href="#"><span>Take the Tour</span></a></li>
			<li><a href="/index/pricing"><span>Pricing</span></a></li>
			<li><a href="work.html"><span>Work</span></a></li>
			<li><a href="/index/about" <?php echo $about?>><span>About</span></a></li>
			<li><a href="/index/contact"><span>Contact</span></a></li>
			<li class="last"><a href="/owners/login"><span>Login</span></a></li>
		</ul>
		<div class="clear"></div>
	</div>
</div>
<!--/ header -->

