<div id="navigation-main" class="navigation-main">
	<ul id="main-nav" class="main-nav">
		<li class="selected">
			<div class="home-icon icon"></div>Home
		</li>
		<li>
			<div class="usergroup-icon icon"></div>User Groups
		</li>
		<li><div class="plugin-icon icon"></div>Your plugin</li>
		<li><div class="leadschat-icon icon"></div>Mobile</li>
		<li><div class="settings-icon icon"></div>Settings</li>
	</ul>
</div>