<footer>
	<div class="footer-line"></div>
	<div class="footer-left">
		<img src="images/leadschat-footer-logo.png" />
		<div class="footer-links">
			<a href="#">TERMS OF SERVICE</a><a href="#" class="last">PRIVATE
				POLICY</a>
		</div>

	</div>
	<div class="footer-center">COPYRIGHT © 2012 LEADS CHAT, LLC. ALL RIGHTS
		RESERVED</div>
	<div class="footer-right">
		<a href="#"><img src="images/fb.png" /></a><a href="#"><img
			src="images/twitter.png" /></a><a href="#"><img src="images/plus.png" /></a><a
			href="#"><img src="images/mail.png" /></a><a href="#" class="last"><img
			src="images/rss.png" /></a>
	</div>
</footer>