<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Leads Chat</title>
    <link href="css/mailtemplate.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div id="maincontainer">
        <div class="content">
            <div class="clipper">
            </div>
            <!-- end .clipper -->
            <div class="logo">
                <img src="img/leadchatlogo.png" alt="Leads Chat Logo" />
            </div>
            <!-- end .logo -->
            <p>
                Hello <strong>Jacob!</strong></p>
            <p>
                Please visit your smartphone's APP store for the <strong><a>LeadsChat Smartphone APP!</a></strong>
            </p>
            <div class="pick-platform">
                <div class="right">
                    <div class="btn-container left">
                        <button class="btn ios">
                        </button>
                        <p>
                            iOS</p>
                    </div>
                    <div class="btn-container left">
                        <button class="btn android">
                        </button>
                        <p>
                            Android</p>
                    </div>
                    <div class="btn-container left">
                        <button class="btn blackberry">
                        </button>
                        <p>
                            Blackberry</p>
                    </div>
                    <div class="btn-container left">
                        <button class="btn hp">
                        </button>
                        <p>
                            HP</p>
                    </div>
                    <div class="btn-container left">
                        <button class="btn windows">
                        </button>
                        <p>
                            Windows Phone</p>
                    </div>
                    <div class="btn-container left">
                        <button class="btn symbian">
                        </button>
                        <p>
                            Symbian</p>
                    </div>
                </div>
            </div>
            <!-- end .pick-platform -->
            <p>
                The <a>LeadsChat.com</a> Dashboard and Smartphone App username and password we will
                be assigning you are identical for your 7 Day Free Trial Account. Once we have assigned
                your password you can keep it the same or you can create a new password. Feel free
                to explore the <a>APP Demo page</a> and <a>Dashboard Demo Page</a> featured on the
                <a>leadschat.com</a> sitemap. An Implementation Specialist will be contacting you
                shortly rregarding your Free Trial Account.</p>
            <p>
                Thank you!
                <br />
                <strong>LeadsChat Team</strong>
            </p>
        </div>
        <!-- end .content -->
        <div class="copyright">
            © 2012 Copyright Leads CHAT. All rights reserved</div>
        <!-- end .copyright -->
    </div>
    <!-- end .maincontainer -->
</body>
</html>